spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/trading-card?currentSchema=card-catalog
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml